### ISSUE TITLE
Q: is there some issue with "debug" gem bundled with ruby 3.2.x

### ISSUE THREAD

**Issue by kikonen** [ruby/debug#898] opened 2023-02-15 13:59 UTC
**Your environment**

* `ruby -v`:  3.2.1
* `rdbg -v`: 1.7.1

**Describe the bug**

Encountering strange problem in circleci due to debug gem,

```
Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
(irb (>= 1.5.0), reline (>= 0.3.1)).
Either installing with `--full-index` or running `bundle update debug` should
fix the problem.
```

i.e. there is no such dependencies in Gemfile.lock generated by bundler in ruby 3.2, I see that in rubygems such dependencies are listed, so is there something wrong with this version "debug" bundled into ruby 3.2.1?

In Gemfile
```
gem 'debug'
```

In Gemfile.lock
```
GEM
...
    debug (1.7.1)
...
DEPENDENCIES
  debug
...
BUNDLED WITH
   2.4.6
```
Thus no dependencies

**To Reproduce**

in circleci when using gem caching this triggers
```
version: 2
jobs:
  test:
    docker:
      - image: ruby:3.2.1
        environment:
          RUBY_YJIT_ENABLE: 'true'
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: |
            ruby --version
            bundle config set --local path vendor/bundle
            bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
```

**Expected behavior**

Clearly I would expect to not get such obscure error, which clearly should not exist

**Additional context**

Have spent now one day of trying to figure out how to make this work, I don't want to remove "debug" gem, since would fix problem, but then I loose debugger

**Comment by doits** [comment] 2023-02-15 15:12
Same for me. The error only happened on CI for me though, locally it installed fine 🤷 . I removed the gem for the time beeing.

**Comment by gregawoods** [comment] 2023-02-15 15:27
Same. Locking debug to version 1.6.1 in my Gemfile has worked for the time being.

**Comment by deivid-rodriguez** [comment] 2023-02-15 19:28
I believe this is an upstream issue, I reported it [a while ago](https://bugs.ruby-lang.org/issues/19158). You can find a workaround [here](https://github.com/ruby/debug/issues/852#issuecomment-1431872261).

**Comment by hsbt** [comment] 2023-02-16 09:01
I fixed this issue at https://bugs.ruby-lang.org/issues/19158#note-10. We need to test it with Ruby 3.2 and backport, cut a new release.

**Comment by searls** [comment] 2023-02-16 12:13
@hsbt thank you!! 💚

**Comment by kikonen** [comment] 2023-02-16 14:05
Lovely

**Comment by doits** [comment] 2023-02-16 18:11
Thanks for your help!

FYI I could fix it by:

- `gem uninstall debug`
- `bundle update` (which reinstalls `debug` with correct dependencies)

**Comment by brand-it** [comment] 2023-02-21 03:42
Came here running into this same problem. For sure there is something odd going on with the bundler and the lock file. I did not spend more than an hour on this problem before giving up and placing the required gems into the group.

### Steps to reproduce Locally 

1. ` bundle config --local deployment true`
2. bundle install
3. 😠 experience frustration(optional)

### Steps to reproduce GitHub actions

```yaml
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
```

I omitted the RSpec step but this will also get you the error if you set up this Github action on a repo

### "Solution"

My solution is sort of a solution but really this should be something the gem does so I came to the conclusion there is a bug in bundler(`2.4.7`)

```ruby
group :development, :test do
  gem 'debug'
  gem 'irb'
  gem 'reline'
end
```

![Screen Shot 2023-02-20 at 7 31 46 PM](https://user-images.githubusercontent.com/13140/220240704-77088e49-125c-4cb4-8cca-0343516a2baa.png)

I don't have an answer to why this is happening but because this gem is for local development I did not dust off many brain cell to figure it out. First time I have seen this hope it is the last. Thanks for the hard work on this gem.

**Comment by hsbt** [comment] 2023-02-22 07:12
> My solution is sort of a solution but really this should be something the gem does so I came to the conclusion there is a bug in bundler(`2.4.7`)

No. This issue is installer bug of Ruby 3.1 and 3.2.

**Comment by dmytro-korzhov-rg** [comment] 2023-02-22 10:15
what worked for me was freezing the debug version to 1.7.0

Gemfile:
`gem 'debug', '1.7.0', platforms: %i[mri mingw x64_mingw]`

dependencies appeared in Gemfile.lock :
`debug (1.7.0)`
`  irb (>= 1.5.0)`
`  reline (>= 0.3.1)`

**Comment by kikonen** [comment] 2023-03-02 12:29
Many workarounds, but do we get permanent fix for this via some way on someday?

**Comment by deivid-rodriguez** [comment] 2023-03-02 12:38
See https://github.com/ruby/debug/issues/898#issuecomment-1432741515. @hsbt fixed this and if you follow the link posted there, you can verify that the fix has already been backported to the stable branches of Ruby 3.1 and Ruby 3.2. It will be available in the next patch level releases.

**Comment by hsbt** [comment] 2023-03-02 21:51
We will release the next Ruby 3.1 and 3.2 versions in March 2023.

**Comment by kikonen** [comment] 2023-03-03 09:04
@hsbt appreciated :)

**Comment by travisdock** [comment] 2023-03-20 11:50
Just got this issue on a fresh rails app in a docker container with ruby 3.2. Just had to do a `bundle update` and it updated irb and then installed debug perfectly fine.

**Comment by hsbt** [comment] 2023-04-03 04:57
This issue has been fixed with Ruby 3.2.2 and 3.1.4.

**Closed by hsbt** 2023-04-03 04:57 UTC

**Comment by nasunaoki** [comment] 2023-04-18 06:05
In this case, the event still occurs in the following cases
Attached log snippet
ruby '3.2.2'
gitlab-runner

```
Running with gitlab-runner 15.9.1 (d540b510)
  on gitlab-runner-8666dd76d6-w2ccj c4Z4xWBH, system ID: r_mGVcBFPGsQa2
Preparing the "kubernetes" executor
00:00
Using Kubernetes namespace: gitlab-runner
Using Kubernetes executor with image public.ecr.aws/docker/library/ruby:3.2.2 ...
Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
(irb (>= 1.5.0), reline (>= 0.3.1)).
Either installing with `--full-index` or running `bundle update debug` should
fix the problem.
```

**Comment by CorbaDigitpaint** [comment] 2023-08-17 13:57
> In this case, the event still occurs in the following cases Attached log snippet ruby '3.2.2' gitlab-runner
> 
> ```
> Running with gitlab-runner 15.9.1 (d540b510)
>   on gitlab-runner-8666dd76d6-w2ccj c4Z4xWBH, system ID: r_mGVcBFPGsQa2
> Preparing the "kubernetes" executor
> 00:00
> Using Kubernetes namespace: gitlab-runner
> Using Kubernetes executor with image public.ecr.aws/docker/library/ruby:3.2.2 ...
> Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
> (irb (>= 1.5.0), reline (>= 0.3.1)).
> Either installing with `--full-index` or running `bundle update debug` should
> fix the problem.
> ```

I can confirm the issue still persist when using ruby:3.2.2 image from dockerhub
