### ISSUE TITLE
why my debugger always hang?

### ISSUE THREAD

**Issue by laptopmutia** [ruby/debug#735] opened 2022-08-12 14:43 UTC
Ruby 3.1.2

rails (7.0.3.1)
debug (1.6.1)
  irb (>= 1.3.6)
  reline (>= 0.3.1)

When I use debugger then write some code
like this
```
(ruby) request.env["omniauth.auth"]
```

it hang and never do anything not even throwing error
but sometimes it returning syntax error

until I manually kill the process

**Comment by st0012** [comment] 2022-08-12 14:46
It may be caused by https://github.com/ruby/debug/issues/725, which has been fixed in `1.6.2`. Can you upgrade and try again?

**Comment by slayer** [comment] 2022-08-12 20:41
Same issue with `1.6.2` - simple method call hangs for ~1 minute

**Comment by prostko** [comment] 2022-08-25 17:22
+1. Hanging and crashing happens more than it doesn't.

**Comment by st0012** [comment] 2022-08-25 18:19
Can you provide a demo app that reproduces the crashing?

**Comment by laptopmutia** [comment] 2022-08-27 02:11
for me 1.6.2 fixed my problem

**Comment by ko1** [comment] 2022-09-16 08:15
can we close this issue?

**Comment by laptopmutia** [comment] 2022-09-16 08:19
yea

**Comment by prostko** [comment] 2022-09-16 18:54
@ko1 I'm still experiencing this issue pretty frequently. I'm happy to open a separate issue when I get some time and add a complete demo app and steps to reproduce. 

Thanks for your work on this 👍

**Comment by ko1** [comment] 2022-09-16 21:38
@prostko Thank you and sorry bothering you.

**Closed by ko1** 2022-09-16 21:38 UTC

**Comment by laptopmutia** [comment] 2022-10-14 16:04
this issues seems back again, I'm wondering even though I have use 1.6.2

**Comment by onesneakymofo** [comment] 2023-01-12 21:11
Macbook Air M2 here chiming in - version 1.7.1.

I am getting 

```
"No live threads left. Deadlock?\n5 threads, 5 sleeps current...
```
when using `binding.break`

**Comment by drewlustro** [comment] 2023-08-14 22:50
Also seeing this. M1 Max, version 1.8.0

Seeing same as @onesneakymofo
