### ISSUE TITLE
Debug gem adds buggy autocomplete in irb

### ISSUE THREAD

**Issue by Mathieuu** [ruby/debug#491] opened 2022-01-12 23:51 UTC
**Describe the bug**
Putting `debug` in the gem file of a rails app adds some autocomplete features to `rails console` and to `irb`. I could not find any mention of that in the issues or in the docs. Is this on purpose?

<img width="760" alt="Screen Shot 2022-01-12 at 2 25 38 PM" src="https://user-images.githubusercontent.com/5503512/149241060-a48e2e64-65a3-405e-aecd-b36e4bbddddf.png">

It doesn't seem like a big deal but that autocomplete is extremely glitchy for my entire team. Delay when typing, sometimes keystrokes completely ignored and once or twice it messed up the display of my entire shell.

**To Reproduce**
See this repo: https://github.com/Mathieuu/DebugPuma/commits/debug-debug-gem

I scaffolded a rails app and added the debug gem

**Comment by st0012** [comment] 2022-01-13 12:49
I think it's because the debugger depends on `irb` and `reline` and newer versions of `reline` has this dialog if `completion_proc` is set. One workaround is to call:

```rb
Reline.completion_proc = nil
```

from either the console or any place after `reline` is required, perhaps `config/initializers/reline.rb` for a Rails app.

I think it also makes sense to add a config option for disabling debugger's `completion_proc` assignment. (`RUBY_DEBUG_NO_RELINE` disables reline completely so it'll also affect input hint messages and it's not an optimal solution for this issue)
However, since the `completion_proc` by default could be assigned by both `irb` and debugger, even if the debugger doesn't enable autocompletion, you'll still see that dialog. So for now I think you need to apply that workaround anyway.

cc @ko1 @aycabta

**Comment by Mathieuu** [comment] 2022-01-13 20:58
I have tried `export RUBY_DEBUG_NO_RELINE=true` and [disabling it in initializer](https://github.com/Mathieuu/DebugPuma/commit/d953dc8a0bd2144b11bda0fde1bf88db8a2f8aa8) but none seems to have any effect. 

The only thing that worked was to run `Reline.completion_proc = nil` in the console directly.

So I tried digging a bit more and ran `bundle open debug`. I removed the[ code loading reline](https://github.com/ruby/debug/blob/master/lib/debug/console.rb#L6) and removed it from the Gem dependencies. But `debug/console.rb` is only evaluated when a breakpoint becomes active, therefore it had no effect. Reline is loaded into the rails console at launch time through another way (still related to that gem though). This explains why the env var flag had no effect I imagine.

**Comment by st0012** [comment] 2022-01-13 21:30
Sorry that I wasn't explain it clearly. But I didn't mean it's caused by debugger's reline usage. I was saying that it could also enable the dialog you see.


To be clear, the root cause is actually not the debugger itself. It's because 
1. debugger requires new version of reline as its dependency, which has this new dialog
2. And then the dialog is enabled by [`irb`'s autocomplete feature](https://github.com/ruby/debug/blob/8f6f02691cbb446c42d759d4fb0c50e32793dae5/lib/debug/console.rb#L43) when you enter the console.

The initializer patch doesn't work probably because `irb`'s setup is only called after an irb session has been started. Other workarounds are:

- Lock `irb` and `reline` versions:

```rb
  gem 'irb', '~> 1.3.6'
  gem 'reline', '~> 0.2.7'
```

- Putting `IRB.conf[:USE_AUTOCOMPLETE] = false` in `PROJECT_DIR/.irbrc` or `~/.irbrc`.

**Comment by ko1** [comment] 2022-02-21 17:50
can we close it?

**Closed** 2022-02-21 17:54 UTC
