### ISSUE TITLE
Requiring "debug" Interferes with Ruby autoloading

### ISSUE THREAD

**Issue by morgoth** [ruby/debug#580] opened 2022-03-24 11:39 UTC
**Your environment**

* `ruby -v`: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]`
* `rdbg -v`: `rdbg 1.4.0`

**Describe the bug**
When `debug` gem is required, it somehow changes how the Ruby `autoload` is working

**To Reproduce**
```ruby
require 'tempfile'
require 'async'
require 'debug' # when I remove this line it works fine

Tempfile.create(['foo', '.rb']) do |file|
  file.write(<<~RUBY)
    class C
      def self.call_me
      end
    end
  RUBY
  file.close

  autoload :C, file.path

  Async do |task|
    3.times do |i|
      task.async do
        p C.call_me
        sleep rand
      end
    end
  end.wait
end
```
it produces:
```
  0.0s    error: Async::Task [oid=0xaf0] [ec=0xb04] [pid=1655265] [2022-03-24 12:35:28 +0100]
               |   NameError: uninitialized constant C
               |   → (irb):19 in `block (4 levels) in <top (required)>'
               |     /home/wojtek/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/async-2.0.1/lib/async/task.rb:258 in `block in schedule'
  0.0s    error: Async::Task [oid=0xb2c] [ec=0xb40] [pid=1655265] [2022-03-24 12:35:28 +0100]
               |   NameError: uninitialized constant C
               |   → (irb):19 in `block (4 levels) in <top (required)>'
               |     /home/wojtek/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/async-2.0.1/lib/async/task.rb:258 in `block in schedule'
nil
=> 3
```

**Expected behavior**
It should not error out when used altogether with [async](https://github.com/socketry/async) gem

**Additional context**
The original report and @fxn investigation that leads to this issue can be found here https://github.com/rails/rails/issues/44751

FYI @fxn @ioquatix @bruno-

**Comment by ko1** [comment] 2022-03-25 07:25
I can repro and the following does not repro.
hmm?

```ruby
require 'debug' # when I remove this line it works fine
require 'async'

autoload :FileUtils, 'fileutils'

Async do |task|
  3.times do |i|
    task.async do
      p FileUtils
    end.wait
  end
end
```

**Comment by ko1** [comment] 2022-03-25 07:34
Ah, fileutils is loaded already.

I can repro with RSS.
```ruby
require 'async'
require 'debug' # when I remove this line it works fine

autoload :RSS, 'rss'

Async do |task|
  3.times do |i|
    task.async do
      p RSS
    end
  end
end.wait
```

**Comment by ioquatix** [comment] 2022-03-25 07:35
@ko1 thanks for investigating.

**Comment by ko1** [comment] 2022-03-25 07:54
Maybe I can understand the situation.

1. access to C -> require a file
2. "require" compiles a file and executes it. TracePoint (`script_compiled`) can intercept a code between compiles and execute. debug.gem inserts some code and code do `Queue#push`. `Queue#push` invokes the fiber scheduler and another task (maybe fiber) are scheduled and run.

Repro code without debug.gem.
```ruby
# prepare '/tmp/foo.rb' before run it.
# echo "class C; end" >> /tmp/foo.rb

require 'async'

q1 = Queue.new
q2 = Queue.new

Thread.new{ loop{
  p q1.pop; q2 << :b
}}
  
TracePoint.new(:script_compiled){|tp|
  q1 << :a
  p q2.pop
}.enable

autoload :C, '/tmp/foo'

Async do |task|
  3.times do |i|
    task.async do
      # require '/tmp/foo'
      p C
    end
  end
end.wait
```

**Comment by ko1** [comment] 2022-03-25 07:57
Another repro code.

```ruby
require 'tempfile'
require 'async'

Tempfile.create(['foo', '.rb']) do |file|
  file.write(<<~RUBY)
    #
    q = Queue.new
    t = Thread.new{q.pop}
    q << :sig
    t.join

    class C
    end
  RUBY
  file.close

  autoload :C, file.path

  Async do |task|
    3.times do |i|
      task.async do
        p C
      end
    end
  end.wait
end
```

I want to close this issue because it is not a debug.gem issue.

**Closed by ko1** 2022-03-25 07:57 UTC

**Comment by fxn** [comment] 2022-03-25 10:06
Threads have constant references synchornized. This works:

```ruby
require 'tempfile'
require 'async'

Tempfile.create(['foo', '.rb']) do |file|
  file.write(<<~RUBY)
    #
    q = Queue.new
    t = Thread.new{q.pop}
    q << :sig
    t.join

    class C
    end
  RUBY
  file.close

  autoload :C, file.path

  Array.new(10) { Thread.new { p C } }.each(&:join)
end
```

So, I believe this is down to constant reference synchronization in the context of fibers.

Could you perhaps @ioquatix get a minimal reproduction with fibers that does not use `async` to arrive to the heart of the matter?

**Comment by fxn** [comment] 2022-03-25 10:10
Sleeping while the `require` is happening is enough to reproduce:

```ruby
require 'tempfile'
require 'async'

Tempfile.create(['foo', '.rb']) do |file|
  file.write(<<~RUBY)
    sleep 0.01
    class C
    end
  RUBY
  file.close

  autoload :C, file.path

  Async do |task|
    3.times do |i|
      task.async { p C }
    end
  end.wait
end
```

**Comment by ioquatix** [comment] 2022-03-25 20:13
https://bugs.ruby-lang.org/issues/18663 for further discussion.

**Comment by ioquatix** [comment] 2022-03-25 20:13
> So, I believe this is down to constant reference synchronization in the context of fibers

A fiber is just a subset of a thread, so it sounds like locking implementation here is incorrect in CRuby. I need to investigate.

**Comment by fxn** [comment] 2022-03-25 20:15
I just created https://bugs.ruby-lang.org/issues/18662.

**Comment by ioquatix** [comment] 2022-03-25 20:16
It looks like we have.... a race condition.

**Comment by fxn** [comment] 2022-03-25 20:16
LOL. Let me close mine!

**Comment by ioquatix** [comment] 2022-03-25 20:17
Ok thanks!

**Comment by fxn** [comment] 2022-03-25 20:26
I can't close! Don't find a way to delete either... have left a message.
